### ISSUE TITLE
Energy generators

### ISSUE THREAD

**Issue by HyperSoop** [Stellarica/Stellarica#115]
Solar, wind, nuclear, and traditional fuel burning. Could also add thermal generators that only work in contact with the ground and can be very expadable for ground bases

**Comment by trainb0y** [comment]
Have to be sure to balance solar and wind properly. HE has the issue where solar panels = infinite free power. There should be *some* cost

**Comment by HyperSoop** [comment]
Well, the downside would be that they'd only work in daytime, other than that, they're kinda supposed to be infinite, just weak if there are few
