### ISSUE TITLE
Holding down precision movement or accelerate does not let you to change direction mid-hold

### ISSUE THREAD

**Issue by HyperSoop** [Stellarica/Stellarica#129]
When you hold down precision movement or accelerate you can't just rotate your camera to start moving in a different direction, you need to release and re-hold the key when you're changed your look direction or else the movement will go into the initial look direction even if you'll have rotated said direction by then.

**Comment by trainb0y** [comment]
The funny thing is it works perfectly fine on my local testing server. I’ll have to look into this more

**Comment by HyperSoop** [comment]
Also works fine on my testing server. Might be a ping issue (tm)

**Comment by trainb0y** [comment]
Going to close this because I can’t reproduce it locally.
