### ISSUE TITLE
Custom Armor System

### ISSUE THREAD

**Issue by trainb0y** [Stellarica/Stellarica#151]
I kind of want to experiment with outright replacing the vanilla armor system, sort of like how Stellar Edge does. Armor would consist of varied "modules" that give small effects or bonuses. The point wouldn't be to have them be gamebreaking or a massive boost in combat, more QoL things like night vision and maybe double jump.

Could probably use armor trims to make the modules visually appear.

**Comment by HyperSoop** [comment]
Can you make it so you can hold an armor item on your cursor, click that item on another item (module), and have them combine? and also right click the armor on an empty slot to get the module back

**Comment by trainb0y** [comment]
I was thinking about having a completely custom GUI. You click on an armor slot, and rather than placing a vanilla armor item in it, it brings up the custom armor screen.

**Comment by HyperSoop** [comment]
that'd be unnesesary complication imo.
