### ISSUE TITLE
Config loading lacks error handling

### ISSUE THREAD

**Issue by trainb0y** [Stellarica/Stellarica#22]
Config loading of custom items, blocks, and multiblocks lack good error handling, and are likely to throw NPE's if the config is formatted incorrectly. Useful error messages would be great.

**Comment by trainb0y1** [comment]
Honestly might be better to use a config-focused library, if a good Kotlin one can be found.

**Comment by Peter-Crawley** [comment]
Configurate

**Comment by trainb0y1** [comment]
> Configurate

Oh that actually looks very useful, especially since it has [this](https://github.com/SpongePowered/Configurate/wiki/Kotlin#object-mapping)

**Comment by Peter-Crawley** [comment]
Ion's configuration handling could be a good example of how to use it.

**Comment by trainb0y** [comment]
Configuration is being completely removed for now, I’ll deal with this eventually:tm:

**Comment by HyperSoop** [comment]
@trainb0y close it as not planned instead, also maybe add this to the project board at lowest priority

**Comment by trainb0y** [comment]
> @trainb0y close it as not planned instead, also maybe add this to the project board at lowest priority

See #60
