### ISSUE TITLE
Hotbar Menu doesn't close

### ISSUE THREAD

**Issue by trainb0y** [Stellarica/Stellarica#23]
Sometimes upon logout or ship unpilot the hotbar menu does not go away, wiping the player's original hotbar.

**Comment by trainb0y1** [comment]
Could have to do with PlayerSwapHandItemsEvent, which is currently not handled.

**Comment by trainb0y** [comment]
Still an issue if the player logs out with it open

**Comment by trainb0y** [comment]
Haven’t run into this in a while, and the hotbar menu will be going poof soon:tm:
