### ISSUE TITLE
Ship movement leaves visual artifacts

### ISSUE THREAD

**Issue by trainb0y** [Stellarica/Stellarica#24]
When moving larger ships they sometimes leave visual artifacts in their wake.
Perhaps `sendMultiBlockChange()` could help?

**Comment by trainb0y1** [comment]
![image](https://user-images.githubusercontent.com/66213737/174921226-4474a658-6d40-4c3f-8ecb-c614da02778c.png)
I mean this could just be the fault of a client mod but I doubt it.

**Comment by Peter-Crawley** [comment]
Definitely a client fault. Make sure your sending the update packets.

**Comment by trainb0y1** [comment]
![2022-06-24_17 16 59](https://user-images.githubusercontent.com/66213737/175726162-a6df1812-4132-498d-b574-b4fa3e159c62.png)

The more complicated the shape, the worse it is.

Also it does in fact happen with a pure vanilla client, it isn't a sodium thing or anything like that.

**Comment by trainb0y1** [comment]
Helped by https://github.com/HydrazineMC/Hydrazine/commit/83c824093b92101ec7f467e9794836641a66f94b but it's still not perfect if the player is too far from that section of the ship. Will need to look into it more later.

**Comment by trainb0y1** [comment]
I know CorsairCraft uses a similar approach, but sends the packet directly, bypassing bukkit nonsense

**Comment by trainb0y** [comment]
Can be somewhat remedied by turning “always defer chunk updates” off on the client
