### ISSUE TITLE
Oka

### ISSUE THREAD

**Issue by HyperSoop** [Stellarica/Stellarica#76]
Dark unhospitable planet with a barren obsidian surface, intended to be an endgame mining area concentrating many end-game and high demand resources.  
The planet is almost fully made of obsidian, and bedrock is scattered all around underground, with more bedrock blocking your way the deeper you go (like the vanilla bedrock fade-in, but it spans around 80 blocks instead of 4), with more loot to be found on deeper Y levels.

Random details & ideas: no/toxic atmosphere, high radiation levels, possible thunderstorms (?); a gas giant moon (?); cracks in the surface going a few blocks down and having crying obsidian at the bottom, spikes with layers of crying obsidian and an increased concentration of bedrock

**Comment by trainb0y** [comment]
Oka is on the test server

**Comment by HyperSoop** [comment]
oka is not complete and the mining part isn't even started on

**Comment by trainb0y** [comment]
reduced tomatoes go talk to novaman
